config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                      uniqueness: { case_sensitive: false },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password                 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new 
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end

  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params 
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
    redirect_to articles_path if logged_in?

  end

  def about; end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Invalid Login"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.username} created successfully"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy 
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all articles deleted"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80, styles: '' })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    style = options[:styles]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, style: style)
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div>
    <h2><%= article.title %></h2>
    <% if article.user %>
      <small>by <%= link_to article.user.username, user_path(article.user) %></small>
    <% end %>
    <% if article.categories.any? %>
      <%= render article.categories %>
    <% end %>
    <p><%= article.description %></p>
    <small>Updated <%= time_ago_in_words(article.updated_at) %> ago</small><br>
    <small>Created: <%= article.created_at %></small>
    <p>
      <span><%= link_to 'View', article_path(article) %></span>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        | 
        <span><%= link_to 'Edit', edit_article_path(article) %></span>
        | 
        <span><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}  %></span>
      <% end %>
    </p>

  </div>
<% end %>

app/views/articles/_form.html.erb
<div>
  <div>
    <div>
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, local: true) do |f| %>
        <div>
          <%= f.label :title %>
          <div>
            <%= f.text_field :title, placeholder: "Title of article" %>
          </div>
        </div>

        <div>
          <%= f.label :description %>
          <div>
            <%= f.text_area :description, rows: 10, placeholder: "Description of article" %>
          </div>
        </div>

        <div>
          <%= f.label :categories %>
          <div>
            <%= f.collection_select(:category_ids, Category.all, :id, :name, 
            { prompt: "Make Your Selections (Not Required)" }, { multiple: true, size: 8 }) %>
          </div>
        </div>

        <div>
          <%= f.submit %>
        </div>
      <% end %>
    </div>
    <div>
      <%= link_to 'Cancel', articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<%= will_paginate @articles %>

<%= render 'article' %>

<p>
  <%= link_to 'Create New Article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<small>by <%= link_to @article.user.username, user_path(@article.user) %></small>
<% if @article.categories.any? %>
  <%= render @article.categories %>
<% end %>
<p><%= @article.description %></p>
<p>
  <small>Updated <%= time_ago_in_words(@article.updated_at) %> ago</small><br>
  <small>Created: <%= @article.created_at %></small><br>
  
</p>
<p>
  <span><%= link_to 'Return', articles_path %></span>
  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
        | 
        <span><%= link_to 'Edit', edit_article_path(@article) %></span>
        | 
        <span><%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}  %></span>
      <% end %>
</p>

app/views/categories/_category.html.erb
<div>
  <%= link_to category.name, category_path(category) %>
</div>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
 <%= form_with(model: @category, local: true) do |f| %>
   <div>
     <%= f.label :name, "Category name" %>
     <div>
       <%= f.text_field :name, placeholder: "Enter a name" %>
     </div>
   </div>

   <div>
     <%= f.submit %>
   </div>
 <% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>
<div>
  <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
</div>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<%= will_paginate @categories %>
<br>

<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category) %>
  <div><%= pluralize(category.articles.count, "article") %></div>
  <small>Created <%= time_ago_in_words(category.created_at) %> ago</small>
  <br />
<% end %>

<p>
  <% if logged_in? && current_user.admin? %>
    <%= link_to 'Create New Category', new_category_path %>
  <% end %>
</p>

app/views/categories/new.html.erb
<h1>Create a New Category</h1>
<div>
  <%= render 'form' %>
</div>
<div>
  <%= link_to '[ Cancel and return to categories listing ]', categories_path %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div>
    <%= link_to "Edit category name", edit_category_path(@category) %>
  </div>
<% end %>

<h3>Articles</h3>

<div>
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

app/views/layouts/_footer.html.erb
<footer>
  <small>Copyright 2021</small>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <div>
      <span>
        <code><%= link_to 'ALPHA BLOG', root_path %></code>
        <%= link_to 'Articles', articles_path %>
        <%= link_to 'Bloggers', users_path %>
        <%= link_to 'About', about_path %>
        <%= link_to 'Categories', categories_path %>
      </span>
      <span style="float: right">
        <% if logged_in? %>
          <%= link_to 'New Post', new_article_path %>
          <%= "Admin -" if current_user.admin? %>
          <%= link_to current_user.username, user_path(current_user) %>
          <%= link_to 'Logout', logout_path, method: :delete %>
        <% else %>  
          <%= link_to 'Sign Up', signup_path %>
          <%= link_to 'Log in', login_path %>
        <% end %>
      </span>
    </div>
    <div>
      <!-- search here -->
    <div>
    
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <small><%= msg %></small>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/simpledotcss/simple.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'Articles listing', articles_path %>

<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<h1>Alpha Blog</h1>

<%= link_to 'Articles Listing', articles_path %>

<%= link_to 'About', about_path %>
<br />
<%= link_to "Sign Up", signup_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <p><b>The following errors prevented the <%= obj.class.name.downcase %> from being saved</b></p>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><mark><%= msg %></mark></li>
    <% end %>
  </ul>
  <hr>
<% end %>

app/views/users/_form.html.erb
<div>
  <div>
    <div>
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, local: true) do |f| %>
        <div>
          <%= f.label :user %>
          <div>
            <%= f.text_field :username, placeholder: "Username" %>
          </div>
        </div>

        <div>
          <%= f.label :email %>
          <div> 
            <%= f.email_field :email,  placeholder: "Email" %>
          </div>
        </div>

        <div>
          <%= f.label :password %>
          <div> 
            <%= f.password_field :password,  placeholder: "Password" %>
          </div>
        </div>

        <div>
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update User") %>
        </div>
      <% end %>
    </div>
    <div>
      <%= link_to 'Cancel', articles_path %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Alpha Blog Users</h1>

<% @users.each do |user| %>
  <div>
    <div><%= gravatar_for user, size: 100, styles: 'width:150px' %></div>
    <div><%= link_to user.username, user %></div>
    <div><%= pluralize(user.articles.count, "article") %></div>
    <small>Joined: <%= time_ago_in_words(user.created_at) %></small>
    <p>
      <span><%= link_to 'View Profile', user_path(user) %></span>
      <% if logged_in? && (user == current_user || current_user.admin?) %>
        | 
        <span><%= link_to 'Edit Profile', edit_user_path(user) %></span>
        | 
        <span><%= link_to 'Delete User', user_path(user), method: :delete, data: {confirm: "Are you sure?"}, style: "color:red"  %></span>
      <% end %>
    </p>
    <hr>

  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<%= gravatar_for @user, size: 100, styles: 'width:150px' %>

<% if logged_in? && (@user == current_user || current_user.admin?) %>
  <%= link_to "Edit your profile", edit_user_path(@user) %>
  <%= link_to "Delete your accout", user_path(current_user), method: :delete, data: { confirm: "Are you sure?" }, style: "color:red"  %>
<% end %>

<h2><%= @user.username %>'s Articles</h2>

<%= render 'articles/article' %>